### ISSUE TITLE
Notice of inclusion/licensing

### ISSUE THREAD

**Issue by getify** [mdkrajnak/ebnftest#2]
No action is necessary on your part here. Just an informational notice. I've included the `ebnftest.js` file (the distribution as deployed to your online tool) in my project, as seen in this commit:

https://github.com/getify/foi-lang/commit/b5bec1dda5c9df9d312069e0c9ba8683b6896b02#diff-2654462590e4d787110317dc05cb32e9b926c5e3300396b6975d713b9178b1a2

I've added the following license header to your file:

```
// From: https://github.com/mdkrajnak/ebnftest
// Copyright © 2016 Michael Krajnak
// Distributed under the Eclipse Public License either version 1.0 or (at your option) any later version.
// EPL 2.0 epl2-license.txt
// Secondary License: MIT https://getify.mit-license.org/
```

Other than this copyright header, I've not made any modifications to your file/code.

Since your copyright statement allows licensing under later versions of EPL, and 1.0 has been deprecated since 2017, I've elected to accept it under the current EPL 2.0 version. I also included the EPL2 license text in a separate file (`epl2-license.txt`) alongside `ebnftest.js`.

Moreover, EPL2 allows for "Secondary License" (generally for GPL compatibility) designation, so I've elected to note that I'm adopting MIT as the secondary license, given that my project is MIT licensed.

----

Thank you for this tool, it's been extremely helpful as I've been developing my project!

**Comment by mdkrajnak** [comment]
Thanks!

I can't remember why I used EPL and I have no strong feelings about licensing this project any specific way, including changing to a more liberal license.

So in that context I'm curious, what is meant by "Secondary License: MIT https://getify.mit-license.org/"?

**Comment by getify** [comment]
> So in that context I'm curious, what is meant by "Secondary License: MIT

This might help provide some additional context: https://www.eclipse.org/legal/epl-2.0/faq.php#h.w1np1lrpht6k

In spirit, the idea (as I understand it) was to allow a more permissively licensed project (i.e., EPL) to include an additional licensing option that could be more restrictive (GPL), for projects that are already GPL and require GPL code. That FAQ says it's very similar to "dual licensing", where a project can be accepted under either of two sets of licensing terms, so long as the including project declares which license set they are choosing to accept.

I sort of turned this around a bit, and chose a permissive license even than EPL, which in my case is MIT, simply because I choose to use MIT for all my own OSS projects.

As far as I can tell, I don't think it would have been invalid for me to just distribute EPL code licensed-as-is in my MIT project, but... since EPL provided the option of the "secondary license" declaration to be more specific, I just thought it would be more clear.

----

IANAL, but as far as I can tell, the outcome here, for my project, is that anyone who derives projects from mine, including using *my distribution* of your ebnf library, *they* are doing so entirely under the guises of MIT (not EPL)... thus they no longer have the option of "secondary licensing" (since that concept is not in MIT)... that is, once I opt to accept your code under MIT, that makes *that copy* (and any future derived copies) of your code licensed entirely as MIT, not the original EPL(+MIT), and that flows forward perpetually.

Of course, since I didn't modify your code in any way, anyone who wanted to, could re-license code directly from you, under EPL (or any other secondary license as they choose), and not accept my MIT distribution of it.

So in the end, I don't think it actually matters that much. I opted this route, only out of respect for your project and wanting to be extremely crisp on the licensing, just in case there were ever any questions. In fact, this thread itself is great documentation (for posterity) about our mutual intentions here. :)
