### ISSUE TITLE
Angle brackets in invalid test string are added as HTML element in error message 

### ISSUE THREAD

**Issue by Lampe2020** [mdkrajnak/ebnftest#3]
I've noticed that test strings are evaluated as HTML if output in an error message.   
I'm not familiar with clojurescript so I can't fix it in a PR, but I know where the problem comes from: the error message is set into the element's `innerHTML` instead of its `innerText`, which would automatically escape HTML characters so they look the same as in the input when rendered. 
Because you're setting the error message in a way that it's tried to be evaluated as HTML it makes some error messages chaotic, especially if you have things like `<i>`, `<b>`, etc. in the test string. It also makes it harder to see where the error pointer is supposed to point, especially when the HTML-rendered text is something like `<div>`, which doesn't immediately look off in the error message but still causes the error arrow to point at the wrong character.   
   
As you can see in the screenshot below, instead of showing `<input>="unclosed string` in the error message, it shows an input field followed by `="unclosed string`: ![Screenshot 2023-07-06 at 19-29-17 EBNF Test](https://github.com/mdkrajnak/ebnftest/assets/94976382/bbb51a4b-0c59-4457-acdd-d7406185c8bc)   
Just so you know, the EBNF syntax you see in the screenshot is for my own esolang.

**Comment by mdkrajnak** [comment]
Can you paste the text above _as text_, or something similar for me to try out?

**Comment by Stehlampe2020** [comment]
This is the significant part of the syntax: 
```EBNF
string          = ( '"', { escape_sequence | #'[^"]' }, '"' ) | ( "'", { escape_sequence | #"[^']" }, "'" ) ;
escape_sequence = "\\", ( '"' | "'" | "\\" ) ;
```
This is one of the more obvious failed cases: 
`<input value="any HTML-like structure you want">&larr;`

**Comment by Lampe2020** [comment]
@mdkrajnak This is the significant part of the syntax:   
```EBNF
assignment_series  = { assignment, ";" } ; (* I've used another separator in my own esolang but it's probably easier for you to type it this way *)
assignment         = variable_reference, "=", string ; (* Obviously this rule is not complete *)
variable_reference = "<", [ ( "0" | "1" | ( #"[a-zA-Z_]", { #"[a-zA-Z0-9_]" } ) ) ], ">" ; (* Condensed down, get the full definition from the file I linked below *)
string             = ( '"', { #'[^"]' | '\\"' }, '"' ) | ( "'", { #"[^']" | "\\'" }, "'" ) ;
```
One of the more obvious failed cases is `<html>='<input type="number" value="3" min="0" max="8">';&circlearrowright;` (it's almost valid, assigning the string `<input type="number" value="3" min="0" max="8">` to the variable called `html`, except that the `&circlearrowright;` doesn't belong there which you can test by removing everything after (and including) the `&` from the test input).   
In this example the error message doesn't visibly contain the `<html>` part and contains an interactable number input that is prefilled with 3 and goes from 0 to 8, also the `&circlearrowright;` is interpreted to `↻`. 
   
As you can see in the example image above, my esolang defines variables by enclosing their name in angle brackets, which coincidentally also is the way XML tags are formed. To get the full EBNF syntax as text you can get it from [my website](https://www.lampe2020.de/extras/test:arrowey/syntax.txt) (the syntax may change as my esolang isn't fully developed yet).

**Comment by Lampe2020** [comment]
Thanks for fixing it :)
